name: CD

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    name: Build Image & Push To ECR
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    environment: CICD
    env:
      ECR_REPO: tiflash-autoscale-supervisor
      AWS_ROLE_ARN: ${{ secrets.TIFLASH_COMPUTE_ECR_AWS_ROLE }}
      AWS_REGION: us-east-2
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
    outputs:
      image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.sha }}
    steps:
      # - name: Check out Code
      #   uses: actions/checkout@v2
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.TIFLASH_COMPUTE_ECR_AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: "linux/amd64,linux/arm64"

      - name: Setup Docker Context
        run: |
          docker --context tls-env info || docker context create tls-env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: tls-env

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Make Sure the Image Repos Exist
        run: |
          aws ecr describe-repositories --repository-names ${{ env.ECR_REPO }} || aws ecr create-repository --repository-name ${{ env.ECR_REPO }} || exit 1
      - name: Build and Push Latest Images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: "linux/amd64,linux/arm64"
          push: true
          build-args: |
            GITHUB_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.sha }}